
import React, { useState } from 'react';
import { Copy, CheckCircle, Database, Shield, BookOpen } from 'lucide-react';

const generateSQLSchema = () => {
  return `
-- ENABLE UUID EXTENSION
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. INSTITUTION TYPES (e.g. University, School)
CREATE TABLE IF NOT EXISTS institution_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. INSTITUTIONS
CREATE TABLE IF NOT EXISTS institutions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type_id UUID REFERENCES institution_types(id),
    manager_id UUID, -- Links to app_users (defined later)
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. ADDRESSES
CREATE TABLE IF NOT EXISTS addresses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    institution_id UUID REFERENCES institutions(id) ON DELETE CASCADE,
    address_line_1 TEXT,
    city TEXT,
    state_province TEXT,
    postal_code TEXT,
    country TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. USER RULES (Roles)
CREATE TABLE IF NOT EXISTS user_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_name TEXT NOT NULL UNIQUE, -- 'Administrator', 'Institution', 'Teacher', 'Student'
    description TEXT,
    enabled BOOLEAN DEFAULT true,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. APP USERS (Extended Profile)
CREATE TABLE IF NOT EXISTS app_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_id UUID UNIQUE, -- Links to Supabase Auth.users.id
    email TEXT UNIQUE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    profile_picture_url TEXT,
    user_rule_id UUID REFERENCES user_rules(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. DEPARTMENTS
CREATE TABLE IF NOT EXISTS departments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code TEXT,
    institution_id UUID REFERENCES institutions(id),
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 7. SCHOOL GRADES
CREATE TABLE IF NOT EXISTS school_grades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL, -- e.g. "9th Grade"
    level INTEGER, -- e.g. 9
    institution_id UUID REFERENCES institutions(id),
    description TEXT,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. PROFESSORS
CREATE TABLE IF NOT EXISTS professors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES app_users(id) NOT NULL,
    department_id UUID REFERENCES departments(id),
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. STUDENTS
CREATE TABLE IF NOT EXISTS students (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES app_users(id) NOT NULL,
    student_hash TEXT UNIQUE NOT NULL, -- Unique identifier generated by system
    grade_id UUID REFERENCES school_grades(id),
    institution_id UUID REFERENCES institutions(id),
    class_id UUID, -- Defined later
    age INTEGER,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. CLASSES
CREATE TABLE IF NOT EXISTS classes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    grade_id UUID REFERENCES school_grades(id),
    institution_id UUID REFERENCES institutions(id),
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Update Student foreign key for class
ALTER TABLE students ADD CONSTRAINT fk_student_class FOREIGN KEY (class_id) REFERENCES classes(id);

-- 11. CLASS_PROFESSORS (Junction)
CREATE TABLE IF NOT EXISTS class_professors (
    class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
    professor_id UUID REFERENCES professors(id) ON DELETE CASCADE,
    PRIMARY KEY (class_id, professor_id)
);

-- 12. DISCIPLINES (Subjects)
CREATE TABLE IF NOT EXISTS disciplines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    grade_id UUID REFERENCES school_grades(id),
    professor_id UUID REFERENCES professors(id), -- Specific teacher for this subject in this grade context (simplified)
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 13. QUESTIONS (Bank)
CREATE TABLE IF NOT EXISTS questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    content TEXT NOT NULL,
    difficulty TEXT, -- 'Easy', 'Medium', 'Hard'
    subject TEXT,
    grade_id UUID REFERENCES school_grades(id),
    image_url TEXT,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 14. QUESTION OPTIONS
CREATE TABLE IF NOT EXISTS question_options (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID REFERENCES questions(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_correct BOOLEAN DEFAULT false,
    key TEXT, -- 'A', 'B', 'C', etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 15. TESTS
CREATE TABLE IF NOT EXISTS tests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    professor_id UUID REFERENCES professors(id),
    grade_id UUID REFERENCES school_grades(id),
    institution_id UUID REFERENCES institutions(id),
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 16. TEST_QUESTIONS (Junction)
CREATE TABLE IF NOT EXISTS test_questions (
    test_id UUID REFERENCES tests(id) ON DELETE CASCADE,
    question_id UUID REFERENCES questions(id) ON DELETE CASCADE,
    weight INTEGER DEFAULT 1,
    order_index INTEGER DEFAULT 0,
    PRIMARY KEY (test_id, question_id)
);

-- 17. TEST_RELEASES (Assignments)
CREATE TABLE IF NOT EXISTS test_releases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id UUID REFERENCES tests(id),
    student_id UUID REFERENCES students(id),
    professor_id UUID REFERENCES professors(id),
    institution_id UUID REFERENCES institutions(id),
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    max_attempts INTEGER DEFAULT 1,
    allow_consultation BOOLEAN DEFAULT false,
    allow_ai_agent BOOLEAN DEFAULT false,
    location_polygon JSONB, -- Array of {lat, lng}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 18. TEST_RESULTS
CREATE TABLE IF NOT EXISTS test_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_id UUID REFERENCES tests(id),
    student_id UUID REFERENCES students(id),
    test_release_id UUID REFERENCES test_releases(id),
    student_name TEXT,
    student_hash TEXT,
    score NUMERIC,
    correct_count INTEGER,
    error_count INTEGER,
    correction_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    image_url TEXT
);

-- 19. STUDENT_TEST_ANSWERS
CREATE TABLE IF NOT EXISTS student_test_answers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_result_id UUID REFERENCES test_results(id) ON DELETE CASCADE,
    question_id UUID REFERENCES questions(id),
    selected_option_id UUID REFERENCES question_options(id),
    is_correct BOOLEAN
);

-- 20. TEST_RESULT_CORRECTION_LOGS
CREATE TABLE IF NOT EXISTS test_result_correction_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_result_id UUID REFERENCES test_results(id) ON DELETE CASCADE,
    question_id UUID REFERENCES questions(id),
    original_option_id UUID REFERENCES question_options(id),
    new_option_id UUID REFERENCES question_options(id),
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 21. TEST_ATTEMPT_LOGS
CREATE TABLE IF NOT EXISTS test_attempt_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_release_id UUID REFERENCES test_releases(id) ON DELETE CASCADE,
    attempt_number INTEGER,
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    preliminary_score NUMERIC,
    restarted BOOLEAN DEFAULT false,
    location_lat NUMERIC,
    location_lng NUMERIC
);

-- 22. AI AGENTS
CREATE TABLE IF NOT EXISTS ai_agents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    role TEXT,
    system_prompt TEXT,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 23. AGENT DOCUMENTS (RAG)
CREATE TABLE IF NOT EXISTS agent_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID REFERENCES ai_agents(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding VECTOR(768), -- Requires pgvector extension
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 24. TEST RELEASE SITES
CREATE TABLE IF NOT EXISTS test_release_sites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_release_id UUID REFERENCES test_releases(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    title TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 25. BNCC (Base Nacional Comum Curricular)
CREATE TABLE IF NOT EXISTS bncc (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo_alfanumerico TEXT NOT NULL,
    descricao_habilidade TEXT,
    ano_serie TEXT,
    componente_curricular TEXT,
    unidade_tematica TEXT,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 26. LIBRARIES
CREATE TABLE IF NOT EXISTS libraries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    grade_id UUID REFERENCES school_grades(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 27. LIBRARY ITEMS
CREATE TABLE IF NOT EXISTS library_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    library_id UUID REFERENCES libraries(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    file_url TEXT NOT NULL,
    file_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Row Level Security (Basic Enablement)
ALTER TABLE institution_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE institutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE disciplines ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_releases ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_test_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_result_correction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_attempt_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_release_sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE bncc ENABLE ROW LEVEL SECURITY;
ALTER TABLE libraries ENABLE ROW LEVEL SECURITY;
ALTER TABLE library_items ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access (For Dev Mode Simplicity) - REPLACE WITH STRICT POLICIES IN PROD
CREATE POLICY "Public Read All" ON institution_types FOR SELECT USING (true);
CREATE POLICY "Public Read Inst" ON institutions FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON user_rules FOR SELECT USING (true);
CREATE POLICY "Public Read Addr" ON addresses FOR SELECT USING (true);
CREATE POLICY "Public Read Rules" ON user_rules FOR SELECT USING (true);
-- ... Add policies for all tables as needed ...
CREATE POLICY "Public Read All" ON app_users FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON departments FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON school_grades FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON professors FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON students FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON classes FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON class_professors FOR SELECT USING (true);
CREATE POLICY "Public Read All" ON disciplines FOR SELECT USING (true);
-- Add other policies as needed for your application's security model.
  `;
};

const SqlSchemaViewer: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [copiedBncc, setCopiedBncc] = useState(false);
  const [copiedAuthLink, setCopiedAuthLink] = useState(false);

  const sql = generateSQLSchema();

  const handleCopy = () => {
    navigator.clipboard.writeText(sql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const authLinkSql = `
-- Function to link auth.users to app_users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.app_users (auth_id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
  `.trim();

  const bnccSql = `
-- ADD BNCC TABLE
CREATE TABLE IF NOT EXISTS bncc (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo_alfanumerico TEXT NOT NULL,
    descricao_habilidade TEXT,
    ano_serie TEXT,
    componente_curricular TEXT,
    unidade_tematica TEXT,
    deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE bncc ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Auth Read BNCC" ON bncc FOR SELECT TO authenticated USING (true);
  `.trim();

  const handleCopyBncc = () => {
      navigator.clipboard.writeText(bnccSql);
      setCopiedBncc(true);
      setTimeout(() => setCopiedBncc(false), 2000);
  }
  
  const handleCopyAuthLink = () => {
    navigator.clipboard.writeText(authLinkSql);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
            <div className="flex justify-between items-start mb-2">
                <h3 className="font-bold text-blue-900 flex items-center gap-2">
                    <Database size={18}/> Full Database Schema
                </h3>
                <button 
                    onClick={handleCopy}
                    className="text-xs bg-white border border-blue-200 text-blue-700 px-3 py-1.5 rounded-lg font-bold hover:bg-blue-100 transition-colors flex items-center gap-2"
                >
                    {copied ? <CheckCircle size={14}/> : <Copy size={14}/>}
                    {copied ? 'Copied!' : 'Copy Full Script'}
                </button>
            </div>
            <div className="bg-slate-900 rounded-lg p-3 overflow-x-auto relative group">
            <div className="bg-slate-900 dark:bg-slate-800 rounded-lg p-3 overflow-x-auto relative group">
                <code className="text-xs text-blue-100 font-mono whitespace-pre block h-48 overflow-hidden">
                    {sql}
                </code>
            </div>
        </div>

        <div className="bg-indigo-50 border border-indigo-200 rounded-lg p-4 mb-6">
        <div className="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800 rounded-lg p-4">
            <div className="flex justify-between items-start mb-2">
                <h3 className="font-bold text-indigo-900 flex items-center gap-2">
                    <BookOpen size={18}/> Add BNCC Table
                </h3>
                <button 
                    onClick={handleCopyBncc}
                    className="text-xs bg-white border border-indigo-200 text-indigo-700 px-3 py-1.5 rounded-lg font-bold hover:bg-indigo-100 transition-colors flex items-center gap-2"
                >
                    {copiedBncc ? <CheckCircle size={14}/> : <Copy size={14}/>}
                    {copiedBncc ? 'Copied!' : 'Copy Script'}
                </button>
            </div>
            <div className="bg-slate-900 rounded-lg p-3 overflow-x-auto relative group">
            <div className="bg-slate-900 dark:bg-slate-800 rounded-lg p-3 overflow-x-auto relative group">
                <code className="text-xs text-indigo-100 font-mono whitespace-pre block h-24 overflow-hidden">
                    {bnccSql}
                </code>
            </div>
        </div>

        <div className="bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg p-4">
            <div className="flex justify-between items-start mb-2">
                <h3 className="font-bold text-emerald-900 flex items-center gap-2">
                    <Shield size={18}/> Auth Link Trigger
                </h3>
                <button 
                    onClick={handleCopyAuthLink}
                    className="text-xs bg-white border border-emerald-200 text-emerald-700 px-3 py-1.5 rounded-lg font-bold hover:bg-emerald-100 transition-colors flex items-center gap-2"
                >
                    {copied ? <CheckCircle size={14}/> : <Copy size={14}/>}
                    {copied ? 'Copied!' : 'Copy Script'}
                </button>
            </div>
            <div className="bg-slate-900 dark:bg-slate-800 rounded-lg p-3 overflow-x-auto relative group">
                <code className="text-xs text-emerald-100 font-mono whitespace-pre block h-40 overflow-hidden">
                    {authLinkSql}
                </code>
            </div>
        </div>
    </div>
  );
};

export default SqlSchemaViewer;
